drop table if exists authors CASCADE
;

drop table if exists books CASCADE
;

drop table if exists books_author_list CASCADE
;

drop table if exists comments CASCADE
;

drop table if exists genres CASCADE
;

drop table if exists users CASCADE
;

drop table if exists users_genre_list CASCADE
;

create table authors (
                         id bigint generated by default as identity,
                         name varchar(255) not null,
                         primary key (id)
)
;

create table books (
                       id bigint generated by default as identity,
                       name varchar(255) not null,
                       genre_id bigint,
                       primary key (id)
)
;

create table books_author_list (
                                   book_id bigint not null,
                                   author_list_id bigint not null
)
;

create table comments (
                          id bigint generated by default as identity,
                          text varchar(255) not null,
                          user_name varchar(255) not null,
                          book_id bigint,
                          primary key (id)
)
;

create table genres (
                        id bigint generated by default as identity,
                        name varchar(255) not null,
                        primary key (id)
)
;

create table users (
                       id varchar(255) generated by default as identity,
                       is_account_non_expired boolean,
                       is_account_non_locked boolean,
                       is_credentials_non_expired boolean,
                       is_enabled boolean,
                       name varchar(255) not null,
                       password varchar(255),
                       role varchar(255),
                       primary key (id)
)
;

create table users_genre_list (
                                  user_id varchar(255) not null,
                                  genre_list_id bigint not null
)
;

alter table authors
    add constraint UK_9mhkwvnfaarcalo4noabrin5j unique (name)
;

alter table books
    add constraint UK_eh6bfj824qyn40pii29i90bll unique (name)
;

alter table genres
    add constraint UK_pe1a9woik1k97l87cieguyhh4 unique (name)
;

alter table users
    add constraint UK_3g1j96g94xpk3lpxl2qbl985x unique (name)
;

alter table books
    add constraint FK9hsvoalyniowgt8fbufidqj3x
        foreign key (genre_id)
            references genres
;

alter table books_author_list
    add constraint FKlkhmvt8tq9xjbmntxbcq4jl9
        foreign key (author_list_id)
            references authors
;

alter table books_author_list
    add constraint FK4tbva6kuwwccb4pjeyu1nyne2
        foreign key (book_id)
            references books
;

alter table comments
    add constraint FK1ey8gegnanvybix5a025vepf4
        foreign key (book_id)
            references books
;

alter table users_genre_list
    add constraint FKpv314qc6bdu7e4esdfxbwr0cl
        foreign key (genre_list_id)
            references genres
;

alter table users_genre_list
    add constraint FKpvskkvqep2wcnyywpds0r4agf
        foreign key (user_id)
            references users
;


------------------------ACL------------------------

CREATE TABLE IF NOT EXISTS acl_sid (
  id bigint(20) NOT NULL AUTO_INCREMENT,
  principal tinyint(1) NOT NULL,
  sid varchar(100) NOT NULL,
  PRIMARY KEY (id),
  UNIQUE KEY unique_uk_1 (sid,principal)
);

CREATE TABLE IF NOT EXISTS acl_class (
  id bigint(20) NOT NULL AUTO_INCREMENT,
  class varchar(255) NOT NULL,
  PRIMARY KEY (id),
  UNIQUE KEY unique_uk_2 (class)
);
 
CREATE TABLE IF NOT EXISTS acl_entry (
  id bigint(20) NOT NULL AUTO_INCREMENT,
  acl_object_identity bigint(20) NOT NULL,
  ace_order int(11) NOT NULL,
  sid bigint(20) NOT NULL,
  mask int(11) NOT NULL,
  granting tinyint(1) NOT NULL,
  audit_success tinyint(1) NOT NULL,
  audit_failure tinyint(1) NOT NULL,
  PRIMARY KEY (id),
  UNIQUE KEY unique_uk_4 (acl_object_identity,ace_order)
);
 
CREATE TABLE IF NOT EXISTS acl_object_identity (
  id bigint(20) NOT NULL AUTO_INCREMENT,
  object_id_class bigint(20) NOT NULL,
  object_id_identity bigint(20) NOT NULL,
  parent_object bigint(20) DEFAULT NULL,
  owner_sid bigint(20) DEFAULT NULL,
  entries_inheriting tinyint(1) NOT NULL,
  PRIMARY KEY (id),
  UNIQUE KEY unique_uk_3 (object_id_class,object_id_identity)
);
 
ALTER TABLE acl_entry
ADD FOREIGN KEY (acl_object_identity) REFERENCES acl_object_identity(id);

ALTER TABLE acl_entry
ADD FOREIGN KEY (sid) REFERENCES acl_sid(id);
 
--
-- Constraints for table acl_object_identity
--
ALTER TABLE acl_object_identity
ADD FOREIGN KEY (parent_object) REFERENCES acl_object_identity (id);

ALTER TABLE acl_object_identity
ADD FOREIGN KEY (object_id_class) REFERENCES acl_class (id);

ALTER TABLE acl_object_identity
ADD FOREIGN KEY (owner_sid) REFERENCES acl_sid (id);

