DROP TABLE IF EXISTS BOOKS;
CREATE TABLE BOOKS (ID BIGINT PRIMARY KEY, NAME VARCHAR(255));

DROP TABLE IF EXISTS AUTHORS;
CREATE TABLE AUTHORS (NAME VARCHAR(255) PRIMARY KEY);

DROP TABLE IF EXISTS GENRES;
CREATE TABLE GENRES (NAME VARCHAR(255) PRIMARY KEY);

DROP TABLE IF EXISTS BOOKS_AUTHORS;
CREATE TABLE BOOKS_AUTHORS (BOOK_ID BIGINT, AUTHOR VARCHAR(255), PRIMARY KEY(BOOK_ID, AUTHOR));

DROP TABLE IF EXISTS BOOKS_GENRES;
CREATE TABLE BOOKS_GENRES (BOOK_ID BIGINT, GENRE VARCHAR(255), PRIMARY KEY(BOOK_ID, GENRE));